### ISSUE TITLE
Cache reference

### ISSUE THREAD

**Issue by arcueid-dev** [Nyashuka/survival_game#1]
https://github.com/Nyashuka/survival_game/blob/957c353b9b681d380e7d81c75e34953d5e0e402a/Assets/_survival_game/Inventory/Inventory.cs#L82-L83

Cache such references `slotFrom.Item.ItemInfo.MaxCountInStack`

**Comment by Nyashuka** [comment]
https://github.com/Nyashuka/survival_game/blob/main/Assets/_survival_game/Inventory/Scripts/Inventory.cs#L82
