### ISSUE TITLE
Cache

### ISSUE THREAD

**Issue by arcueid-dev** [Nyashuka/survival_game#2]
https://github.com/Nyashuka/survival_game/blob/957c353b9b681d380e7d81c75e34953d5e0e402a/Assets/_survival_game/Inventory/InventorySlot.cs#LL7C58-L7C87

Since you set your info, you can cache `Item.ItemInfo.MaxCountInStack`

**Comment by Nyashuka** [comment]
https://github.com/Nyashuka/survival_game/blob/main/Assets/_survival_game/Inventory/Scripts/InventorySlot.cs#L7
