### ISSUE TITLE
Public set

### ISSUE THREAD

**Issue by arcueid-dev** [Nyashuka/survival_game#3]
https://github.com/Nyashuka/survival_game/blob/957c353b9b681d380e7d81c75e34953d5e0e402a/Assets/_survival_game/Inventory/InventoryUI/InventoryItemUI.cs#L16

Avoid public setters, replace with special method

**Comment by Nyashuka** [comment]
https://github.com/Nyashuka/survival_game/blob/main/Assets/_survival_game/Inventory/Scripts/InventoryUI/InventoryItemUI.cs#L19
