### ISSUE TITLE
Prefabs and scripts

### ISSUE THREAD

**Issue by arcueid-dev** [Nyashuka/survival_game#4]
![image](https://user-images.githubusercontent.com/22265817/229309298-6d4fbd84-c9a2-4289-87d4-537d2ff2fc4d.png)

Keep prefabs and scripts separately.
And create such folder arhitecture

|--Assets
|---Scripts
|----InventoryUI
|-----Inventory.cs
|-----InvetoryItem.cs
|---Prefabs
|----InventoryUI.prefab

**Comment by Nyashuka** [comment]
https://github.com/Nyashuka/survival_game/tree/main/Assets/_survival_game/Inventory
